#!/usr/bin/env bash

# Function to display information about a subdomain
display_subdomain_info() {
    dig_output=$(dig "$1" | grep -A1 'ANSWER SECTION:')
    record_type=$(echo "${dig_output}" | awk '{print $4}')
    destination=$(echo "${dig_output}" | awk '{print $5}')
    echo "The subdomain $2 is a $record_type record and points to $destination"
}

# Main script
if [ "$#" -eq 2 ]; then
    display_subdomain_info "$2.$1" "$2"
else
    display_subdomain_info "www.$1" "www"
    display_subdomain_info "lb-01.$1" "lb-01"
    display_subdomain_info "web-01.$1" "web-01"
    display_subdomain_info "web-02.$1" "web-02"
fi
