#!/usr/bin/env bash
# Shows information about subdomains.

setting_domain() {
	local domain="$1"
	local subdomain="$2"
    
	if [ -z "$subdomain" ]; then
		subdomains=("www" "lb-01" "web-01" "web-02")
	else
		subdomains="$2"
	fi

	for s in "${subdomains[@]}"; do
		rt=$(dig "$s.$domain" | awk '/ANSWER SECTION/ { getline; print $4 }')
		dest=$(dig "$s.$domain" | awk '/ANSWER SECTION/ { getline; print $5 }')
		echo "The subdomain $s is a $rt record and points to $dest"
	done
}

setting_domain "$1" "$2"
