#!/usr/bin/env bash
# displaying domains and subdomain

display_domain_subdomain () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if ["$#" -eq 2 ]
then
    display_domain_subdomain "$2.$1" "$2"
else
    display_domain_subdomain "www.$1" "www"
    display_domain_subdomain "lb-01.$1" "lb-01"
    display_domain_subdomain "web-01.$1" "web-01"
    display_domain_subdomain "web-02.$1" "web-02"
fi

display_domain_subdomain "$1" "$2"
