#!/usr/bin/env bash

# Update the package list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Set up a custom index page with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Configure Nginx to redirect a specific endpoint (/redirect_me to https://sipho.tech)
redirect_config="server_name _;\n\trewrite ^\/redirect_me https:\/\/sipho.tech permanent;"
sudo sed -i "s/server_name _;/$redirect_config/" /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo service nginx restart

