#!/usr/bin/env bash

# Update the package list
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Create a custom HTML file
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Configure Nginx for redirection
redirect_config="location /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}"
sudo sed -i "/server_name _;/a $redirect_config" /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo service nginx restart
