#!/usr/bin/env bash
#moving redirect

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

redirect_config="server_name _;\n\trewrite ^\/redirect_me https:\/\/sipho.tech permanent;"
sudo sed -i "s/server_name _;/$redirect_config/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
error_config="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$error_config/" /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo service nginx restart

