#!/usr/bin/env bash
# Installing Nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i '53s|.*|\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n|' /etc/nginx/sites-enabled/default
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/c_404.html
sudo sed -i '53r /dev/stdin' /etc/nginx/sites-enabled/default <<< "        error_page 404 /c_404.html;
        location = /c_404.html {
                 root /var/www/html;
                 internal;
        }"
sudo service nginx restart
