#!/usr/bin/env bash
# Deploy a new web server with Nginx

# Uncomment to see the script run in action
# set -x

echo -e "Updating and doing some minor checks...\n"

function install() {
    command -v "$1" &> /dev/null

    if [ $? -ne 0 ]; then
        echo -e "Installing: $1\n"
        sudo apt-get update -y -qq && \
            sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "${1} is already installed.\n"
    fi
}

install nginx

echo -e "\nSetting up some minor stuff.\n"

# Allowing Nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
web_dir="/var/www"
if [ -d "$web_dir" ]; then
    sudo chown -R "$USER":"$USER" "$web_dir"
    sudo chmod -R 755 "$web_dir"
else
    sudo mkdir -p "$web_dir"
    sudo chown -R "$USER":"$USER" "$web_dir"
    sudo chmod -R 755 "$web_dir"
fi

# Create directories if not present
for dir in "$web_dir"/{html,error}; do
    if ! [ -d "$dir" ]; then
        mkdir -p "$dir"
    fi
done

# Creating new index
echo "Hello World!" > "$web_dir"/html/index.html

# Create new error page
echo "Ceci n'est pas une page" > "$web_dir"/html/error_404.html

# Backup default server config file
sudo cp /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default_backup

# Create a new server configuration file
server_config=$(cat <<EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root $web_dir/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Served-By \$hostname;
    location / {
        try_files \$uri \$uri/ =404;
    }
    if (\$request_filename ~ redirect_me) {
        rewrite ^ https://th3-gr00t.tk/ permanent;
    }
    error_page 404 /error_404.html;
    location = /error_404.html {
        internal;
    }
}
EOL
)

# Create a new server config file
sudo echo "$server_config" | sudo tee /etc/nginx/sites-available/web_server

# Enable the new server config by creating a symlink
sudo ln -s /etc/nginx/sites-available/web_server /etc/nginx/sites-enabled/

# Test Nginx configuration
sudo nginx -t

# Restart Nginx
sudo service nginx restart

