#!/usr/bin/env bash

# debugging nginx port 80
# Fix: Change port in Nginx configuration, restart Nginx, and kill the nginx process
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo pkill -o nginx
