#!/usr/bin/env bash
# Check if a username is provided as an argumeni
sed -i "s/80/8080/g" /etc/nginx/sites-available/defaulti
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo -u nginx service nginx start
